source $HOME/.bashrc

PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
_byobu_sourced=1 . /usr/local/Cellar/byobu/5.133/bin/byobu-launch 2>/dev/null || true
source "$HOME/.cargo/env"
export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"
